---
title: "p8105_hw5_bp2678"
author: "Brady Pham"
date: 2023-11-13
output: github_document
---
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(rvest)
library(broom)
library(purrr)
set.seed(1)
```

#Question 2 

#Loaded the files and data frame in 
```{r message=FALSE, warning=FALSE}
files_df <- 
  tibble(
    files = list.files('data'),
    path = str_c("data/", files, sep = "/")
  ) |>
  mutate(data = map(path, read_csv)) |>
  unnest(cols = c(data))
```

#Tidy up the data

```{r}
tidy_files_df <- files_df %>%
  mutate(files = str_replace(files, ".csv", ""),
         files = str_replace(files, "con", "control"),
         files = str_replace(files, "exp", "experiment")) %>%
  rename(arm_subject_id = files) %>%
  separate(arm_subject_id, into = c("arm", "subject_id"), sep = "_") %>%
  pivot_longer(cols = starts_with("week"),
               names_to = "week",
               values_to = "value") %>%
  select(-path) %>%
  mutate(week = as.numeric(gsub("week_", "", week)))

  


```

```{r}

ggplot(tidy_files_df, aes(x = week, y = value, color = subject_id)) +
  geom_point() +
  geom_line() +
  labs(title = "Difference Between Control and Experiment Group Over 8 Weeks",
       x = "Week",
       y = "Value") +
  theme_bw() +
  facet_grid(. ~ arm)
```

In the experiment group it shows that there is a general trend of the value increasing as the weeks go by. However, in the control group it seems to remain the same as the weeks go by and that there isn't much change. 

#Question 3 


```{r}

compare_mu_values_map <- function(mu_values = c(0, 1, 2, 3, 4, 5, 6), n = 30, sigma = 5, num_datasets = 5000, alpha = 0.05) {

  datasets <- replicate(num_datasets, rnorm(n, mean = 0, sd = sigma), simplify = FALSE)


  results <- map_df(mu_values, function(mu) {
    map_df(datasets, function(dataset) {
      t_test_result <- t.test(dataset, mu = mu)
      tidy_results <- tidy(t_test_result)
      data.frame(mu = mu, estimated_mean = tidy_results$estimate, p_value = tidy_results$p.value)
    })
  })

  return(results)
}

result_df <- compare_mu_values_map()

```
